- name: configure /etc/aliases
  lineinfile:
    dest: /etc/aliases
    line: "{{ item.user }}: {{ item.alias }}"
    regexp: "^{{ item.user }}:"
  with_items: '{{aliases}}'
  become: yes
  notify: update aliases database
